name: Nala Tests

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  action:
    name: Running E2E & IT
    if: contains(github.event.pull_request.labels.*.name, 'run-nala')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af6833
      - name: Run Nala
        uses: adobecom/nala@main
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          branch: ${{ github.event.pull_request.head.ref }}
          repoName: ${{ github.repository }}
